### ISSUE TITLE
Break to several gems

### ISSUE THREAD

**Issue by atimin** [rmodbus/rmodbus#17]
It's really controversial proposal. But I offer to break rmodbus to gems by type of protocol:
1. 'rmodbus-core'  - core library
2. 'rmodbus-tcp' - Modbus-TCP 
3. 'rmodbus-rtu'  - ModBus-RTU
4. 'rmodbus-rtu-tcp' - ModBus RTU via TCP
5. 'rmodbus' - full distributive 

This model are relieving dependency at such times when you use only tcp protocol. Furthermore I have plan to implemente ModBus over USB which will require new runtime dependency.

Also I offer to separate protocols on modules:

``` ruby
require 'modbus-rtu'

ModBus::RTU::Client.new("/dev/ttyS1") do |cl|
  ...
end
```

**Comment by ccutrer** [comment]
This is unnecessary; the only gem dependency that could be eliminated is gserver, which isn't strictly a dependency. It's up to users to include that gem in their Gemfile in order to use that feature. You could do the same for USB - not list it as a hard dependency. As for runtime avoiding unnecessary requires - that is also done, since the transport-specific classes are autoloaded, so will only require their dependencies if referenced.
